export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const USER_REPOSITORY = 'ROLE_REPOSITORY';
export const NETWOR_MEMBER_REPOSITORY = 'NETWOR_MEMBER_REPOSITORY';
export const NETWORK_REPOSITORY = 'NETWORK_REPOSITORY';
export const NETWORK_ONE_TIME_PAYMENT_REPOSITORY =
  'NETWORK_ONE_TIME_PAYMENT_REPOSITORY';
export const INVITATION_REPOSITORY = 'INVITATION_REPOSITORY';
export const NETWORK_DATABASE_REPOSITORY = 'NETWORK_DATABASE_REPOSITORY';
